version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation package package --template-file template.yaml --s3-bucket andrii-tutyk-cicd-hw  --output-template-file output-template.yaml
artifacts:
  files:
    - target/HelloWorld-1.0.jar
    - output-template.yaml
